
create table state_covid(
    date int
    state text
    positive int
    negative int
    pending int
    totalTestResults int
    hospitalizedCurrently int
    hospitalizedCumulative int
    inIcuCurrently int
    inIcuCumulative int
    onVentilatorCurrently int
    onVentilatorCumulative int
    recovered int
    dataQualityGrade text
    lastUpdateEt text
    dateModified text
    checkTimeEt text
    death int
    hospitalized int
    dateChecked text
    totalTestsViral int
    positiveTestsViral int
    negativeTestsViral int
    positiveCasesViral int
    deathConfirmed int
    deathProbable int
    totalTestEncountersViral int
    totalTestsPeopleViral int
    totalTestsAntibody int
    positiveTestsAntibody int
    negativeTestsAntibody int
    totalTestsPeopleAntibody int
    positiveTestsPeopleAntibody int
    negativeTestsPeopleAntibody int
    totalTestsPeopleAntigen int
    positiveTestsPeopleAntigen int
    totalTestsAntigen int
    positiveTestsAntigen int
    fips text
    positiveIncrease int
    negativeIncrease int
    total int
    totalTestResultsSource text
    totalTestResultsIncrease int
    posNeg int
    deathIncrease int
    hospitalizedIncrease int
    hash text
    commercialScore int
    negativeRegularScore int
    negativeScore int
    positiveScore int
    score int
    grade text
);
